Implementation of the StableDag data structure
mitchmindtree/daggy pull request #21
Opened 2018-09-06 21:25 UTC by davenza

This is an early implementation of a StableDag.The code is almost copied from the Dag structure, but using StableGraph instead of Graph.  As indicated in the original commit, there are 4 methods that are not implemented because StableGraph does not provide the necessary functions:

    raw_nodes() -> Because StableGraph lacks raw_nodes().
    node_weights_mut() -> Because StableGraph lacks node_weights_mut().
    raw_edges() -> Because StableGraph lacks raw_edges().
    edge_weights_mut() -> Because StableGraph lacks edge_weights_mut().

I included the same set of tests for StableDag that is used in the Dag structure in the files
tests/add_edges_stable.rs
tests/iterators_stable.rs
tests/walkers_stable.rs

I also included the tests in tests/stable_indices to test that node/edge indices do not change when we remove an edge/node.

I am pretty new to Rust, so it may need some better code / project organization.

2018-10-04 07:11 UTC, mitchmindtree requested changes
Thanks so much @davenza, this is really great stuff! I've been meaning to get around to this for a while, I can definitely see myself using this down the track.

I just have a couple very minor things to clean up - otherwise I'm more than happy to merge!

So sorry for the delay by the way, it's getting a little overwhelming maintaining what must be ~50 crates by now, whilst also working at my own business! Thanks for being patient with me :)

2018-10-04 07:11 UTC, mitchmindtree commented on src/stabledag.rs
> +    /// Read from the internal edge array.
We probably don't need these commented methods - we likely won't ever implement them as I believe the way edges are stored differs between the `Graph` and `StableGraph`.

2018-10-04 07:11 UTC, mitchmindtree commented on src/stabledag.rs
> +pub struct WouldCycle<E>(pub E);
I think I'd prefer if we re-used the `WouldCycle` error from the crate root rather than declaring a new one for `StableDag`. It might just make error handling downstream a bit easier in cases where the user is working with both `Dag`s and `StableDag`s.

2018-10-04 07:11 UTC, mitchmindtree commented on src/stabledag.rs
> +
unnecessary space

2018-10-04 17:02 UTC, davenza commented
Hi, thanks for you review. I made the changes you asked for. They are in 5482078. 

Then, I added a feature called `stable_dag` for conditional compilation in cf752f4. What do you think about this?

2018-10-04 17:22 UTC, davenza commented
I forgot to include conditional compilation in the tests, but it should be solved in cce14bc.

2018-10-13 15:42 UTC, davenza reviewed
Reviewed changes.

2019-09-13 20:32 UTC, fwcd commented
Any updates on this PR? I would love to help if there are any specific issues, especially in regard to https://github.com/RustAudio/dsp-chain/issues/103.

2019-09-14 02:24 UTC, mitchmindtree commented
Thanks for the reminder @fwcd!

2019-09-14 02:24 UTC, mitchmindtree approved these changes

2019-09-14 02:24 UTC, merged